apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: tools
spec:
  replicas: 3
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - name: jenkins
        image: gcr.io/iti-2-358616/jenkins
        ports:
          - name: http-port
            containerPort: 8080
        volumeMounts:
            - name: jenkins-data
              mountPath: /home/jenkins_home         
      volumes:
        - name: jenkins-data
          persistentVolumeClaim:
              claimName: jenkins-pv-claim