
apiVersion: apps/v1
kind: Deployment
metadata:
  name: website
  namespace: apps
spec:
  replicas: 3
  selector:
    matchLabels:
      app: website
  template:
    metadata:
      labels:
        app: website
    spec:
      containers:
      - name: website
        image: gcr.io/iti-2-358616/website:latest
        ports:
          - name: http-port
            containerPort: 80